# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-21 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='website',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
