# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='featured_image',
            field=models.FileField(null=True, upload_to='featured/'),
        ),
    ]
